# Generated by Django 4.2.6 on 2023-11-01 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('gris', 'Gris'), ('negro', 'Negro'), ('blanco', 'Blanco'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo')], default='blanco', max_length=10)),
                ('plate', models.CharField(default='', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('editionDate', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingPlace', models.CharField(max_length=100)),
                ('arrivalPlace', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('departureTime', models.TimeField()),
                ('travelDate', models.DateField()),
                ('numseatsfree', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('editionDate', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('passengers', models.ManyToManyField(blank=True, related_name='trips_joined', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo_disponible', models.ForeignKey(blank=True, default='Sin vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculo')),
            ],
        ),
    ]
