# Generated by Django 4.2.6 on 2023-10-17 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingPlace', models.CharField(max_length=100)),
                ('arrivalPlace', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('departureTime', models.TimeField()),
                ('travelDate', models.DateField()),
                ('numseatsfree', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('editionDate', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo_disponible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='app.vehiculo')),
            ],
        ),
    ]
