# Generated by Django 4.2.6 on 2023-10-17 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehiculo_disponible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculo'),
        ),
    ]
