# Generated by Django 4.2.6 on 2023-10-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_trip_details_alter_trip_vehiculo_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='vehiculo_disponible',
            field=models.ForeignKey(blank=True, default='Sin vehículo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculo'),
        ),
    ]
