# Generated by Django 4.2.6 on 2023-10-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_trip_vehiculo_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='numseats',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='plate',
            field=models.CharField(default='xxx-###', max_length=10),
        ),
    ]
