# Generated by Django 4.2.6 on 2023-10-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_vehiculo_numseats_vehiculo_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='plate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
